import type { ProviderDescriptor } from "../descriptors/provider.js"

export const PROVIDERS: Record<string, ProviderDescriptor> = {
  anthropic: {
    id: "anthropic",
    vendor: "anthropic",
    name: "Anthropic",
    transport: "anthropic-native",
    authType: "api-key",
    envVar: "ANTHROPIC_API_KEY",
    baseUrl: "https://api.anthropic.com/v1",
    defaultModel: "claude-sonnet-4-20250514",
    models: [
      "claude-sonnet-4-20250514",
      "claude-3-opus-20240229",
      "claude-3-5-sonnet-20241022",
      "claude-3-5-haiku-20241022",
    ],
    description: "Claude models — best for coding",
  },
  openai: {
    id: "openai",
    vendor: "openai",
    name: "OpenAI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "OPENAI_API_KEY",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1", "o3-mini", "gpt-4.1"],
    description: "GPT models",
  },
  codex: {
    id: "codex",
    vendor: "openai",
    name: "Codex OAuth",
    transport: "codex",
    authType: "oauth",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-5.5",
    models: ["gpt-5.5", "gpt-4o", "o3", "o4-mini"],
    description: "Free tier via browser login",
  },
  openrouter: {
    id: "openrouter",
    vendor: "openrouter",
    name: "OpenRouter",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "OPENROUTER_API_KEY",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "openai/gpt-4o",
    models: ["openai/gpt-4o", "anthropic/claude-sonnet-4", "google/gemini-2.5-pro", "deepseek/deepseek-r1"],
    description: "200+ models via one key",
  },
  gemini: {
    id: "gemini",
    vendor: "google",
    name: "Google Gemini",
    transport: "gemini",
    authType: "api-key",
    envVar: "GEMINI_API_KEY",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    defaultModel: "gemini-2.5-pro",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
    description: "Google's latest models",
  },
  deepseek: {
    id: "deepseek",
    vendor: "deepseek",
    name: "DeepSeek",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "DEEPSEEK_API_KEY",
    baseUrl: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    models: ["deepseek-chat", "deepseek-reasoner"],
    description: "Strong reasoning models",
  },
  groq: {
    id: "groq",
    vendor: "groq",
    name: "Groq",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "GROQ_API_KEY",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    models: ["llama-3.3-70b-versatile", "mixtral-8x7b-32768", "gemma2-9b-it"],
    description: "Ultra-fast inference",
  },
  ollama: {
    id: "ollama",
    vendor: "ollama",
    name: "Ollama",
    transport: "openai-compatible",
    authType: "none",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "qwen2.5-coder:7b",
    models: ["qwen2.5-coder:7b", "qwen2.5-coder:14b", "codellama:7b", "codellama:13b", "deepseek-r1:8b", "llama3.1:8b"],
    description: "Local models — no API key needed",
  },
  mistral: {
    id: "mistral",
    vendor: "mistral",
    name: "Mistral",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "MISTRAL_API_KEY",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "codestral-latest",
    models: ["codestral-latest", "mistral-large-latest", "mistral-small-latest"],
    description: "Codestral coding model",
  },
  together: {
    id: "together",
    vendor: "together",
    name: "Together AI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "TOGETHER_API_KEY",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    models: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen2.5-Coder-32B-Instruct", "deepseek-ai/DeepSeek-R1"],
    description: "Open-source model hosting",
  },
  fireworks: {
    id: "fireworks",
    vendor: "fireworks",
    name: "Fireworks AI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "FIREWORKS_API_KEY",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    models: ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/qwen2p5-coder-32b-instruct", "accounts/fireworks/models/deepseek-r1"],
    description: "Fast open-source inference",
  },
  perplexity: {
    id: "perplexity",
    vendor: "perplexity",
    name: "Perplexity",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "PERPLEXITY_API_KEY",
    baseUrl: "https://api.perplexity.ai",
    defaultModel: "sonar-pro",
    models: ["sonar-pro", "sonar", "sonar-reasoning-pro"],
    description: "Search-augmented models",
  },
  cerebras: {
    id: "cerebras",
    vendor: "cerebras",
    name: "Cerebras",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "CEREBRAS_API_KEY",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "llama-3.3-70b",
    models: ["llama-3.3-70b", "llama-3.1-8b"],
    description: "Wafer-scale inference",
  },
  sambanova: {
    id: "sambanova",
    vendor: "sambanova",
    name: "SambaNova",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "SAMBANOVA_API_KEY",
    baseUrl: "https://api.sambanova.ai/v1",
    defaultModel: "Meta-Llama-3.3-70B-Instruct",
    models: ["Meta-Llama-3.3-70B-Instruct", "Qwen2.5-Coder-32B-Instruct", "DeepSeek-R1"],
    description: "Enterprise AI inference",
  },
  xai: {
    id: "xai",
    vendor: "xai",
    name: "xAI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "XAI_API_KEY",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-2-latest",
    models: ["grok-2-latest", "grok-2-1212", "grok-beta"],
    description: "Grok models",
  },
  cohere: {
    id: "cohere",
    vendor: "cohere",
    name: "Cohere",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "COHERE_API_KEY",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    defaultModel: "command-r-plus",
    models: ["command-r-plus", "command-r", "command-a-03-2025"],
    description: "Command-R models",
  },
  ai21: {
    id: "ai21",
    vendor: "ai21",
    name: "AI21 Labs",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "AI21_API_KEY",
    baseUrl: "https://api.ai21.com/studio/v1",
    defaultModel: "jamba-1.5-large",
    models: ["jamba-1.5-large", "jamba-1.5-mini"],
    description: "Jamba hybrid models",
  },
  replicate: {
    id: "replicate",
    vendor: "replicate",
    name: "Replicate",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "REPLICATE_API_KEY",
    baseUrl: "https://openai-proxy.replicate.com/v1",
    defaultModel: "meta/meta-llama-3.1-405b-instruct",
    models: ["meta/meta-llama-3.1-405b-instruct", "meta/meta-llama-3-70b-instruct"],
    description: "Run any model via API",
  },
  huggingface: {
    id: "huggingface",
    vendor: "huggingface",
    name: "Hugging Face",
    transport: "openai-compatible",
    authType: "bearer",
    envVar: "HF_TOKEN",
    baseUrl: "https://api-inference.huggingface.co/v1",
    defaultModel: "Qwen/Qwen2.5-Coder-32B-Instruct",
    models: ["Qwen/Qwen2.5-Coder-32B-Instruct", "meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-R1"],
    description: "Inference API for HF models",
  },
  bedrock: {
    id: "bedrock",
    vendor: "aws",
    name: "Amazon Bedrock",
    transport: "openai-compatible",
    authType: "bearer",
    envVar: "AWS_BEARER_TOKEN_BEDROCK",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    defaultModel: "anthropic.claude-sonnet-4-20250514-v1:0",
    models: ["anthropic.claude-sonnet-4-20250514-v1:0", "anthropic.claude-3-5-sonnet-20241022-v2:0", "meta.llama3-1-70b-instruct-v1:0"],
    description: "AWS managed models",
  },
  "azure-openai": {
    id: "azure-openai",
    vendor: "azure",
    name: "Azure OpenAI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "AZURE_OPENAI_API_KEY",
    baseUrl: "https://YOUR_RESOURCE.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1"],
    description: "Azure-hosted OpenAI models",
  },
  vertex: {
    id: "vertex",
    vendor: "google",
    name: "Vertex AI",
    transport: "openai-compatible",
    authType: "bearer",
    envVar: "GOOGLE_APPLICATION_CREDENTIALS",
    baseUrl: "https://us-central1-aiplatform.googleapis.com/v1",
    defaultModel: "gemini-2.5-pro",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "claude-sonnet-4@20250514"],
    description: "Google Cloud AI platform",
  },
  cloudflare: {
    id: "cloudflare",
    vendor: "cloudflare",
    name: "Cloudflare AI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "CLOUDFLARE_API_TOKEN",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/YOUR_ACCOUNT_ID/ai/v1",
    defaultModel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    models: ["@cf/meta/llama-3.3-70b-instruct-fp8-fast", "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b"],
    description: "Workers AI edge inference",
  },
  github: {
    id: "github",
    vendor: "github",
    name: "GitHub Models",
    transport: "openai-compatible",
    authType: "bearer",
    envVar: "GITHUB_TOKEN",
    baseUrl: "https://models.inference.ai.azure.com",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "Claude-3.5-Sonnet", "Llama-3.3-70B-Instruct", "DeepSeek-R1"],
    description: "Free models with GitHub token",
  },
  lmstudio: {
    id: "lmstudio",
    vendor: "lmstudio",
    name: "LM Studio",
    transport: "openai-compatible",
    authType: "none",
    baseUrl: "http://localhost:1234/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    description: "Local GUI model runner",
  },
  jan: {
    id: "jan",
    vendor: "jan",
    name: "Jan",
    transport: "openai-compatible",
    authType: "none",
    baseUrl: "http://localhost:1337/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    description: "Local open-source ChatGPT",
  },
  vllm: {
    id: "vllm",
    vendor: "vllm",
    name: "vLLM",
    transport: "openai-compatible",
    authType: "none",
    baseUrl: "http://localhost:8000/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    description: "Self-hosted vLLM server",
  },
  textgen: {
    id: "textgen",
    vendor: "oobabooga",
    name: "Text Gen WebUI",
    transport: "openai-compatible",
    authType: "none",
    baseUrl: "http://localhost:5000/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    description: "Oobabooga text-generation-webui",
  },
  litellm: {
    id: "litellm",
    vendor: "litellm",
    name: "LiteLLM",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "LITELLM_API_KEY",
    baseUrl: "http://localhost:4000/v1",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "claude-sonnet-4-20250514", "gemini-2.5-pro"],
    description: "Unified proxy for 100+ LLMs",
  },
  anyscale: {
    id: "anyscale",
    vendor: "anyscale",
    name: "Anyscale",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "ANYSCALE_API_KEY",
    baseUrl: "https://api.endpoints.anyscale.com/v1",
    defaultModel: "meta-llama/Meta-Llama-3.3-70B-Instruct",
    models: ["meta-llama/Meta-Llama-3.3-70B-Instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
    description: "Ray-based inference",
  },
  lepton: {
    id: "lepton",
    vendor: "lepton",
    name: "Lepton AI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "LEPTON_API_KEY",
    baseUrl: "https://llama3-3-70b.lepton.run/api/v1",
    defaultModel: "llama3-3-70b",
    models: ["llama3-3-70b", "deepseek-r1"],
    description: "Serverless GPU inference",
  },
  octoai: {
    id: "octoai",
    vendor: "octoai",
    name: "OctoAI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "OCTOAI_API_KEY",
    baseUrl: "https://text.octoai.run/v1",
    defaultModel: "meta-llama-3.3-70b-instruct",
    models: ["meta-llama-3.3-70b-instruct", "qwen-2.5-coder-32b-instruct"],
    description: "Optimized inference platform",
  },
  deepinfra: {
    id: "deepinfra",
    vendor: "deepinfra",
    name: "DeepInfra",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "DEEPINFRA_API_KEY",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen2.5-Coder-32B-Instruct", "deepseek-ai/DeepSeek-R1"],
    description: "Pay-per-token inference",
  },
  friendli: {
    id: "friendli",
    vendor: "friendli",
    name: "FriendliAI",
    transport: "openai-compatible",
    authType: "api-key",
    envVar: "FRIENDLI_API_KEY",
    baseUrl: "https://inference.friendli.ai/v1",
    defaultModel: "meta-llama-3.3-70b-instruct",
    models: ["meta-llama-3.3-70b-instruct", "Qwen/Qwen2.5-Coder-32B-Instruct"],
    description: "Orca-optimized inference",
  },
  "codex-cli": {
    id: "codex-cli",
    vendor: "openai",
    name: "Codex CLI",
    transport: "codex",
    authType: "oauth",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "o4-mini",
    models: ["o4-mini", "gpt-4o", "o3"],
    description: "OpenAI Codex CLI auth",
  },
  warp: {
    id: "warp",
    vendor: "warp",
    name: "Warp",
    transport: "openai-compatible",
    authType: "oauth",
    baseUrl: "https://api.warp.dev/v1",
    defaultModel: "warp-code",
    models: ["warp-code", "gpt-4o", "claude-sonnet-4-20250514"],
    description: "Warp terminal AI",
  },
  custom: {
    id: "custom",
    vendor: "custom",
    name: "Custom",
    transport: "custom",
    authType: "api-key",
    envVar: "CUSTOM_API_KEY",
    baseUrl: "http://localhost:8080/v1",
    defaultModel: "custom-model",
    models: ["custom-model"],
    description: "Any OpenAI-compatible endpoint",
  },
}

export function getProvider(name: string): ProviderDescriptor | undefined {
  return PROVIDERS[name]
}

export function listProviders(): ProviderDescriptor[] {
  return Object.values(PROVIDERS)
}

export function findProviderByModel(model: string): ProviderDescriptor | undefined {
  return Object.values(PROVIDERS).find((p) => p.models.includes(model))
}

export function findProviderByEnvVar(): ProviderDescriptor | undefined {
  for (const provider of Object.values(PROVIDERS)) {
    if (provider.envVar && process.env[provider.envVar]) {
      return provider
    }
  }
  return undefined
}
