export { providerCommand } from "./provider.js"
export { modelCommand } from "./model.js"
export { oauthCommand } from "./oauth.js"
export { renderSetupPrompt, processSetupSelection, renderApiKeyPrompt } from "./setup.js"
export type { SetupResult } from "./setup.js"

export { compactCommand } from "./compact.js"
export { forkCommand } from "./fork.js"
export { resumeCommand } from "./resume.js"
export { rewindCommand } from "./rewind.js"
export { branchCommand } from "./branch.js"
export { renameCommand } from "./rename.js"

export { diffCommand } from "./diff.js"
export { reviewCommand } from "./review.js"
export { lintCommand } from "./lint.js"
export { securityCommand } from "./security.js"
export { testCommand } from "./test.js"

export { costCommand } from "./cost.js"
export { doctorCommand } from "./doctor.js"
export { statsCommand } from "./stats.js"
export { contextCommand } from "./context.js"
export { historyCommand, addToHistory } from "./history.js"

export { updateCommand } from "./update.js"
export { installCommand } from "./install.js"
export { memoryCommand } from "./memory.js"
export { themeCommand, getCurrentTheme } from "./theme.js"
export type { ArgentTheme } from "./theme.js"
export { vimCommand, isVimMode } from "./vim.js"
export { voiceCommand, isVoiceMode } from "./voice.js"

export { specCommand } from "./spec.js"
export { initCommand } from "./init.js"
export { prCommand } from "./pr.js"
export { issueCommand } from "./issue.js"
export { fixCommand } from "./fix.js"
export { explainCommand } from "./explain.js"

export { paletteCommand } from "./palette.js"
export type { PaletteAction } from "./palette.js"
export { shortcutsCommand } from "./shortcuts.js"
