import type { ArgentEngine } from "../engine.js"
import { execSync } from "child_process"

export function prCommand(args: string[], engine: ArgentEngine): string {
  const lines: string[] = []

  lines.push("")
  lines.push("╔══════════════════════════════════════════╗")
  lines.push("║       Create Pull Request                ║")
  lines.push("╚══════════════════════════════════════════╝")
  lines.push("")

  const wd = engine.config.getWorkingDir()
  const title = args.join(" ") || ""

  try {
    execSync("git status --porcelain", { cwd: wd, encoding: "utf-8", timeout: 5000 })
  } catch {
    lines.push("  Not a git repository.")
    return lines.join("\n")
  }

  let currentBranch = ""
  try {
    currentBranch = execSync("git branch --show-current", { cwd: wd, encoding: "utf-8", timeout: 5000 }).trim()
  } catch {
    currentBranch = "unknown"
  }

  lines.push(`  Branch: ${currentBranch}`)

  let staged = ""
  try {
    staged = execSync("git diff --cached --stat", { cwd: wd, encoding: "utf-8", timeout: 10000 }).trim()
  } catch {
    // no staged changes
  }

  let unstaged = ""
  try {
    unstaged = execSync("git diff --stat", { cwd: wd, encoding: "utf-8", timeout: 10000 }).trim()
  } catch {
    // no unstaged changes
  }

  if (!staged && !unstaged) {
    lines.push("")
    lines.push("  No changes to create a PR from.")
    lines.push("  Make changes first, then run /pr.")
    return lines.join("\n")
  }

  if (unstaged) {
    lines.push("")
    lines.push("  You have unstaged changes.")
    lines.push("  These will NOT be included in the PR.")
    lines.push("  Use 'git add' to stage changes first.")
  }

  if (!staged) {
    lines.push("")
    lines.push("  No staged changes to commit.")
    lines.push("  Stage files with 'git add' first.")
    return lines.join("\n")
  }

  let repoInfo = ""
  try {
    repoInfo = execSync("git remote get-url origin 2>/dev/null || true", { cwd: wd, encoding: "utf-8", timeout: 5000,     shell: process.platform === "win32" ? "powershell.exe" : "/bin/sh" }).trim()
  } catch {
    repoInfo = ""
  }

  if (repoInfo) {
    lines.push(`  Remote: ${repoInfo}`)
  }

  const summaryLine = staged.split("\n").pop() || ""
  lines.push("")
  lines.push(`  Changes: ${summaryLine}`)

  if (!title) {
    lines.push("")
    lines.push("  Usage: /pr <title>")
    lines.push("  Example: /pr Add user authentication")
    lines.push("")
    lines.push("  PR creation requires:")
    lines.push("    1. A commit message (derived from title)")
    lines.push("    2. Push access to the remote")
    lines.push("    3. GitHub CLI (gh) installed for automation")
    return lines.join("\n")
  }

  try {
    execSync("gh --version", { encoding: "utf-8", timeout: 5000 })
  } catch {
    lines.push("")
    lines.push("  GitHub CLI (gh) is not installed.")
    lines.push("  Install it from: https://cli.github.com/")
    lines.push("")
    lines.push("  Or create the PR manually:")
    lines.push(`    git commit -m "${title}"`)
    lines.push(`    git push origin ${currentBranch}`)
    return lines.join("\n")
  }

  lines.push("")
  lines.push(`  Creating PR: ${title}`)

  try {
    const escapedTitle = title.replace(/'/g, "'\\''")
    const result = execSync(`gh pr create --title '${escapedTitle}' --body "Auto-generated by ARGENT" 2>&1`, {
      cwd: wd,
      encoding: "utf-8",
      timeout: 30000,
      shell: process.platform === "win32" ? "powershell.exe" : "/bin/sh",
    })

    lines.push("")
    lines.push(`  ● PR created successfully!`)
    lines.push(`  ${result.trim()}`)
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string; message?: string }
    const output = (e.stdout || e.stderr || "").trim()
    if (output) {
      lines.push("")
      lines.push(`  ${output}`)
    } else {
      lines.push(`  ● PR creation failed: ${e.message || "Unknown error"}`)
    }
  }

  return lines.join("\n")
}
